In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from datetime import datetime

In [2]:
# ------------------------------------------------------------------------------------------------------------
## Vamos a cargar los datos de Investigadores UTB...
# ------------------------------------------------------------------------------------------------------------
datautb=pd.read_excel("Base de Datos Scopus.xlsx")
datautb=datautb.rename(columns={"ID SCOPUS":"Autor ID"})
datautb["Autor ID"]=datautb["Autor ID"].astype("str")

In [3]:
# Generar query para Scopus: https://www.scopus.com/search/form.uri?display=advanced
search1,search2=[],[]
for j,i in enumerate(datautb["Autor ID"]):
    print("AU-ID ( {} )".format(i)+" OR ", end=' ')

AU-ID ( 57156565000 ) OR  AU-ID ( 14622047600 ) OR  AU-ID ( 24329839300 ) OR  AU-ID ( 57194034904 ) OR  AU-ID ( 57193533853 ) OR  AU-ID ( 24537991200 ) OR  AU-ID ( 36142156300 ) OR  AU-ID ( 57039103600 ) OR  AU-ID ( 56674579200 ) OR  AU-ID ( 57210822856 ) OR  AU-ID ( 57191333650 ) OR  AU-ID ( 7005142049 ) OR  AU-ID ( 57193012270 ) OR  AU-ID ( 55649334800 ) OR  AU-ID ( 26325154200 ) OR  AU-ID ( 55872162200 ) OR  AU-ID ( 35788581800 ) OR  AU-ID ( 57024211000 ) OR  AU-ID ( 56801043600 ) OR  AU-ID ( 56380539800 ) OR  AU-ID ( 57188841051 ) OR  AU-ID ( 57202285682 ) OR  AU-ID ( 57350116000 ) OR  AU-ID ( 58525252300 ) OR  AU-ID ( 57192930752 ) OR  AU-ID ( 57200615582 ) OR  AU-ID ( 58660078000 ) OR  AU-ID ( 57190688459 ) OR  AU-ID ( 57208719994 ) OR  AU-ID ( 55258973100 ) OR  AU-ID ( 57203321995 ) OR  AU-ID ( 57220927199 ) OR  AU-ID ( 57193252278 ) OR  AU-ID ( 57322375300 ) OR  AU-ID ( 57205400052 ) OR  AU-ID ( 57758796500 ) OR  AU-ID ( 56581610900 ) OR  AU-ID ( 57392556500 ) OR  AU-ID ( 56682785300 ) OR  AU-ID ( 57219403758 ) OR  AU-ID ( 57197327858 ) OR  AU-ID ( 57196040759 ) OR  AU-ID ( 57220077867 ) OR  AU-ID ( 57750422100 ) OR  AU-ID ( 57223851529 ) OR  AU-ID ( 57189892062 ) OR  AU-ID ( 57205658483 ) OR  AU-ID ( 58068307100 ) OR  AU-ID ( 57197807415 ) OR  AU-ID ( 57918628600 ) OR  AU-ID ( 57222278899 ) OR  AU-ID ( 7195913974 ) OR  AU-ID ( 57218294431 ) OR  AU-ID ( 57206773929 ) OR  AU-ID ( 58068069000 ) OR  AU-ID ( 57216868622 ) OR  AU-ID ( 57930663300 ) OR  AU-ID ( 58523557700 ) OR  AU-ID ( 57204842254 ) OR  AU-ID ( 58618811100 ) OR  AU-ID ( 57201036449 ) OR  AU-ID ( 57209248085 ) OR  AU-ID ( 57212006168 ) OR  AU-ID ( 57427876200 ) OR  AU-ID ( 57204847841 ) OR  AU-ID ( 57195913859 ) OR  AU-ID ( 57218297655 ) OR  AU-ID ( 57222223605 ) OR  AU-ID ( 57221229836 ) OR  AU-ID ( 58803522300 ) OR  AU-ID ( 55783129400 ) OR  AU-ID ( 57903699900 ) OR  AU-ID ( 58954857900 ) OR  AU-ID ( 57202159706 ) OR  AU-ID ( 57219626251 ) OR  AU-ID ( 57215557867 ) OR  AU-ID ( 57219506381 ) OR  AU-ID ( 58134344400 ) OR  AU-ID ( 58917134900 ) OR  AU-ID ( 58153979500 ) OR  AU-ID ( 58868256900 ) OR  AU-ID ( 57918232800 ) OR  AU-ID ( 59987226300 ) OR

### Copiar y pegar 
el último statement y agregar a la linea siguiente. Esta será usada en el sitio de "Advance Search" de Scopus: https://www.scopus.com/search/form.uri?display=advanced...

(AF-ID ( 60103889 ))

### Copiar y pegar 
esta linea anterior en: https://www.scopus.com/search/form.uri?display=advanced, descargar el archivo que genera con los docmentos.

In [4]:
## ------------------------------------------------------------------------------------------------------------------------
## Cargando el archivo de datos de publicaciones Scopus descargado desde la página de Scopus
## ------------------------------------------------------------------------------------------------------------------------
scopus=pd.read_csv("scopus_export_Nov 17-2025_a94fe888-7d6a-4ee6-8173-5e443745e000.csv")

In [5]:
scopus

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,Page end,Page count,Cited by,DOI,Link,Document Type,Publication Stage,Open Access,Source,EID
0,"Saini, P.; Osorio, J.D.; Shah, M.P.; Patel, U....","Saini, Prashant (58622409300); Osorio, Julian ...",58622409300; 55538541600; 58278698400; 5738468...,Nature-inspired lotus-shaped fins combined wit...,2026,International Journal of Heat and Mass Transfer,255,NaN,127897,NaN,NaN,0,0,10.1016/j.ijheatmasstransfer.2025.127897,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-105017763405
1,"Rico-Alvariño, A.; Taboada, M.; Mendoza, L.; N...","Rico-Alvariño, Alberto (54929851700); Taboada,...",54929851700; 60168334100; 60168263700; 6017154...,VACS: A Modular Software System for Vehicular ...,2026,Communications in Computer and Information Sci...,2702 CCIS,NaN,NaN,222,232,0,0,10.1007/978-3-032-08206-0_19,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-105020807503
2,"Tovar, A.M.; C.V.; Martinez-Santos, J.C.; E.","Tovar, Andrea Menco (59500271400); Martinez-Sa...",59500271400; 60171513900; 60168191600; 6017151...,"SAPSAI – System for Acquisition, Preprocessing...",2026,Communications in Computer and Information Sci...,2702 CCIS,NaN,NaN,327,338,0,0,10.1007/978-3-032-08206-0_28,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-105020787948
3,"L.M.; G.S.; A.A.; Villa, J.L.; Duque, J.","; Villa, J. L. (7005142049); Duque, Jorge Elie...",60170646800; 60171318000; 60171094500; 7005142...,Intelligent Real-Time Power Quality Monitoring...,2026,Communications in Computer and Information Sci...,2702 CCIS,NaN,NaN,233,244,0,0,10.1007/978-3-032-08206-0_20,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-105020779857
4,"Rico-Alvariño, A.; Taboada, M.; Mendoza, L.; M...","Rico-Alvariño, Alberto (54929851700); Taboada,...",54929851700; 60168334100; 60168263700; 6016819...,An Optimized Approach for Automatic License Pl...,2026,Communications in Computer and Information Sci...,2701 CCIS,NaN,NaN,223,233,0,0,10.1007/978-3-032-08203-9_19,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-105020672925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1760,"Villa, J.L.V.; Duque, M.; Gauthier, A.; Rakoto...","Villa, J. L. (7005142049); Duque, Mauricio Ism...",7005142049; 7004864427; 7102084702; 6603389671,MLD control of hybrid systems: Application to ...,2003,Proceedings of the IEEE International Conferen...,1,NaN,NaN,666,671,0,8,NaN,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-0242657944
1761,"Villa, J.L.V.; Duque, M.; Gauthier, A.; Rakoto...","Villa, J. L. (7005142049); Duque, Mauricio Ism...",7005142049; 7004864427; 7102084702; 6603389671,Modeling and control of a water treatment plant,2003,Proceedings of the IEEE International Conferen...,1,NaN,NaN,171,176,0,5,NaN,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-0242577256
1762,"Villa, J.L.V.; Duque, M.; Gauthier, A.; Rakoto...","Villa, J. L. (7005142049); Duque, Mauricio Ism...",7005142049; 7004864427; 7102084702; 6603389671,Supervision and optimal control of a class of ...,2003,IEEE International Conference on Emerging Tech...,2,January,1248693,177,180,0,5,10.1109/ETFA.2003.1248693,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-79961012788
1763,"Rakoto, N.; Villa, J.L.V.","Rakoto, Naly (6603389671); Villa, J. L. (70051...",6603389671; 7005142049,Modeling and simulation of an experimental man...,2003,Lecture Notes in Computer Science,2667,NaN,NaN,533,538,0,0,10.1007/3-540-44839-x_57,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,NaN,Scopus,2-s2.0-35248818284
1764,"Rakoto, N.; Villa, J.L.V.; Morel, D.","Rakoto, Naly (6603389671); Villa, J. L. (70051...",6603389671; 7005142049; 7101971552,Supervisory Control Oriented Modeling of an Ex...,2003,IEEE International Symposium on Intelligent Co...,NaN,NaN,NaN,395,398,0,1,10.1109/isic.2003.1254666,https://www.scopus.com/inward/record.uri?eid=2...,Conference paper,Final,NaN,Scopus,2-s2.0-0344235175

In [6]:
## ------------------------------------------------------------------------------------------------------------------------
## Cargando el archivo de datos de publicaciones Scimago descargado desde la página de Scimago
## ------------------------------------------------------------------------------------------------------------------------
#scimago=pd.read_excel("scimagojr2024.xlsx")
scimago=pd.read_csv("scimagojr2024.csv",delimiter=";")

In [7]:
scimago

,Rank,Sourceid,Title,Type,Issn,SJR,SJR Best Quartile,H index,Total Docs. (2024),Total Docs. (3years),...,Ref. / Doc.,%Female,Overton,SDG,Country,Region,Publisher,Coverage,Categories,Areas
0,1,28773,Ca-A Cancer Journal for Clinicians,journal,"15424863, 00079235","145,004",Q1,223,43,122,...,"62,88",-,4,37,United States,Northern America,John Wiley and Sons Inc,1950-2025,Hematology (Q1); Oncology (Q1),Medicine
1,2,19434,MMWR Recommendations and Reports,journal,"10575987, 15458601","41,754",Q1,155,6,15,...,"275,33",-,1,5,United States,Northern America,Centers for Disease Control and Prevention (CDC),1990-2024,Epidemiology (Q1); Health Information Manageme...,Environmental Science; Health Professions; Med...
2,3,20315,Nature Reviews Molecular Cell Biology,journal,"14710072, 14710080","37,353",Q1,531,125,337,...,"92,45",-,0,15,United Kingdom,Western Europe,Nature Research,2000-2025,Cell Biology (Q1); Molecular Biology (Q1),"Biochemistry, Genetics and Molecular Biology"
3,4,29431,Quarterly Journal of Economics,journal,"00335533, 15314650","35,995",Q1,322,48,143,...,"69,79",-,35,27,United Kingdom,Western Europe,Oxford University Press,1886-2025,Economics and Econometrics (Q1),"Economics, Econometrics and Finance"
4,5,20425,Nature Reviews Drug Discovery,journal,"14741784, 14741776","30,506",Q1,412,247,718,...,"35,66",-,1,58,United Kingdom,Western Europe,Nature Research,2002-2025,Drug Discovery (Q1); Medicine (miscellaneous) ...,"Medicine; Pharmacology, Toxicology and Pharmac..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31131,31132,145515,Waves in Random and Complex Media (discontinued),journal,"17455049, 17455030",NaN,-,54,308,1068,...,"49,05",-,0,20,United Kingdom,Western Europe,Taylor and Francis Ltd.,2005-2024,Engineering (miscellaneous); Physics and Astro...,Engineering; Physics and Astronomy
31132,31133,21101174249,Word and Music Studies,book series,15660958,NaN,-,8,16,21,...,"79,44",-,0,0,Netherlands,Western Europe,Brill: Rodopi,"1999-2001, 2004-2006, 2008, 2010-2011, 2014-20...",Arts and Humanities (miscellaneous); Literatur...,Arts and Humanities
31133,31134,18033,"World Dredging, Mining and Construction",trade journal,10450343,NaN,-,3,2,32,...,0,-,0,1,United States,Northern America,Placer Management Corp.,"1979, 1988-2024",Building and Construction; Ocean Engineering; ...,Earth and Planetary Sciences; Engineering
31134,31135,21100898632,World Scientific-Now Publishers Series in Busi...,book series,22513442,NaN,-,3,9,22,...,"31,33",-,0,0,Singapore,Asiatic Region,World Scientific,"2018-2020, 2023-2024","Business, Management and Accounting (miscellan...","Business, Management and Accounting"
31135,31136,18200156701,Zeitschrift Kunststofftechnik/Journal of Plast...,journal,18642217,NaN,-,10,20,0,...,"18,2",-,0,9,Germany,Western Europe,Walter de Gruyter GmbH,"2005-2020, 2024",Polymers and Plastics,Materials Science

In [8]:
## ------------------------------------------------------------------------------------------------------------------------
## Este pedazo de script cruza ambos archivos anteriores (Scopus y Scimago) para añadir una columna en "Scopus"
## que se llama "Best Quartile" que corresponde a la publicación de cada una de las lineas de "Scopus"...
## ------------------------------------------------------------------------------------------------------------------------

best_quartile = []
for i in range(len(scopus)):
    journal = str(scopus.loc[i, "Source title"]).strip().lower()
    best = scimago.loc[scimago["Title"].str.strip().str.lower() == journal, "SJR Best Quartile"].values
    best_quartile.append(best[0] if len(best) == 1 else np.nan)

scopus["Best Quartile"] = best_quartile

#best_quartile=[]
#for i in range(len(scopus)):
#    journal=scopus["Source title"][i]
#    best=scimago.loc[scimago["Title"]==journal]["SJR Best Quartile"].values
#    if len(best)==1:
#        best_quartile.append(best[0])
#    else:
#        best_quartile.append(np.nan)
#    #print(journal,best)

#scopus["Best Quartile"]=best_quartile
scopus.head(1)

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,...,Page count,Cited by,DOI,Link,Document Type,Publication Stage,Open Access,Source,EID,Best Quartile
0,"Saini, P.; Osorio, J.D.; Shah, M.P.; Patel, U....","Saini, Prashant (58622409300); Osorio, Julian ...",58622409300; 55538541600; 58278698400; 5738468...,Nature-inspired lotus-shaped fins combined wit...,2026,International Journal of Heat and Mass Transfer,255,NaN,127897,NaN,...,0,0,10.1016/j.ijheatmasstransfer.2025.127897,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-105017763405,Q1

In [9]:
## ------------------------------------------------------------------------------------------------------------------------
## Este bloque de script genera un nuevo dataframe limpio que contiene todas las publicaciones con información de 
## tipo de publicación, curatil, etc....
## ------------------------------------------------------------------------------------------------------------------------

data_clean = scopus.copy()  # ← tabla final con cuartil
# --------------------------------------------------------------------
# 4. Explosión a nivel autor-artículo
#    (autor ID es muy fiable; si no está, usa nombre)
# --------------------------------------------------------------------
def explode_authors(row):
    ids   = str(row["Author(s) ID"]).split(";")
    names = str(row["Author full names"]).split(";")
    for aid, aname in zip(ids, names):
        aid = aid.strip()
        aname = aname.strip()
        if aid:
            yield {
                "author_id": aid,
                "author_name": aname,
                "year": int(row["Year"]),
                "citations": row.get("Cited by", np.nan),
                "publication": row.get("Title"),
                "journal": row.get("Source title"),
                "volume": row.get("Volume", np.nan),
                "issue": row.get("Issue", np.nan),
                "doi": row.get("DOI", np.nan),
                "document type": row.get("Document Type", np.nan),
                "quartile": row.get("Best Quartile", np.nan)
            }

author_rows = []
for _, r in data_clean.iterrows():
    author_rows.extend(list(explode_authors(r)))

auth_df = pd.DataFrame(author_rows)

In [10]:
auth_df

,author_id,author_name,year,citations,publication,journal,volume,issue,doi,document type,quartile
0,58622409300,"Saini, Prashant (58622409300)",2026,0,Nature-inspired lotus-shaped fins combined wit...,International Journal of Heat and Mass Transfer,255,NaN,10.1016/j.ijheatmasstransfer.2025.127897,Article,Q1
1,55538541600,"Osorio, Julian D. (55538541600)",2026,0,Nature-inspired lotus-shaped fins combined wit...,International Journal of Heat and Mass Transfer,255,NaN,10.1016/j.ijheatmasstransfer.2025.127897,Article,Q1
2,58278698400,"Shah, Munjal Purnkant (58278698400)",2026,0,Nature-inspired lotus-shaped fins combined wit...,International Journal of Heat and Mass Transfer,255,NaN,10.1016/j.ijheatmasstransfer.2025.127897,Article,Q1
3,57384683400,"Patel, Umang N. (57384683400)",2026,0,Nature-inspired lotus-shaped fins combined wit...,International Journal of Heat and Mass Transfer,255,NaN,10.1016/j.ijheatmasstransfer.2025.127897,Article,Q1
4,59963703400,"Nelapudi, Akhil (59963703400)",2026,0,Nature-inspired lotus-shaped fins combined wit...,International Journal of Heat and Mass Transfer,255,NaN,10.1016/j.ijheatmasstransfer.2025.127897,Article,Q1
...,...,...,...,...,...,...,...,...,...,...,...
7696,6603389671,"Rakoto, Naly (6603389671)",2003,0,Modeling and simulation of an experimental man...,Lecture Notes in Computer Science,2667,NaN,10.1007/3-540-44839-x_57,Article,NaN
7697,7005142049,"Villa, J. L. (7005142049)",2003,0,Modeling and simulation of an experimental man...,Lecture Notes in Computer Science,2667,NaN,10.1007/3-540-44839-x_57,Article,NaN
7698,6603389671,"Rakoto, Naly (6603389671)",2003,1,Supervisory Control Oriented Modeling of an Ex...,IEEE International Symposium on Intelligent Co...,NaN,NaN,10.1109/isic.2003.1254666,Conference paper,NaN
7699,7005142049,"Villa, J. L. (7005142049)",2003,1,Supervisory Control Oriented Modeling of an Ex...,IEEE International Symposium on Intelligent Co...,NaN,NaN,10.1109/isic.2003.1254666,Conference paper,NaN
7700,7101971552,"Morel, Dominique (7101971552)",2003,1,Supervisory Control Oriented Modeling of an Ex...,IEEE International Symposium on Intelligent Co...,NaN,NaN,10.1109/isic.2003.1254666,Conference paper,NaN

In [11]:
## ------------------------------------------------------------------------------------------------------------------------
## GET h-index-all and h5yr-index
## ------------------------------------------------------------------------------------------------------------------------

def h_index_from_citations(cites):
    """
    cites: iterable de enteros (citas por artículo)
    retorna: h-index (int)
    """
    # Limpieza básica
    vals = [max(0, int(x)) for x in cites if x == x]  # quita NaN y negativos
    vals.sort(reverse=True)
    # cuenta cuántos cumplen c >= i (con i=1..n) en orden descendente
    return sum(c >= i+1 for i, c in enumerate(vals))
    
def h_index_author(auth_df, author_id, min_year=None, max_year=None):
    sub = auth_df[auth_df["author_id"] == str(author_id)]
    if min_year is not None:
        sub = sub[sub["year"] >= min_year]
    if max_year is not None:
        sub = sub[sub["year"] <= max_year]
    return h_index_from_citations(sub["citations"])

In [12]:
# ------------------------------------------------------------------------------------------------------------
# Probando generación de h-index y h5yr-index
# ------------------------------------------------------------------------------------------------------------

# h-index total del autor
h_all = h_index_author(auth_df, "24329839300")
# h-index de los últimos 5 años (ajusta el rango que quieras)
import datetime
y = datetime.datetime.now().year
h_5yr = h_index_author(auth_df, "24329839300", min_year=y-5, max_year=y)
print(h_all, h_5yr)

13 10

In [ ]:
q1_2025,q2_2025,q3_2025,q4_2025,sq_2025=[],[],[],[],[]
q1_2024,q2_2024,q3_2024,q4_2024,sq_2024=[],[],[],[],[]
q1_2023,q2_2023,q3_2023,q4_2023,sq_2023=[],[],[],[],[]
q1_2022,q2_2022,q3_2022,q4_2022,sq_2022=[],[],[],[],[]
h,h5,autor_sc,nameautor=[],[],[],[]
y = datetime.datetime.now().year
for i in auth_df["author_id"].unique():
    autor_sc.append(i)
    nameautor.append(auth_df[auth_df["author_id"]==i]["author_name"].unique()[0])
    h.append(h_index_author(auth_df, i))
    h5.append(h_index_author(auth_df, i, min_year=y-5, max_year=y))
    q1_2025.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2025)&(auth_df["quartile"]=="Q1")]))
    q2_2025.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2025)&(auth_df["quartile"]=="Q2")]))
    q3_2025.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2025)&(auth_df["quartile"]=="Q3")]))
    q4_2025.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2025)&(auth_df["quartile"]=="Q4")]))
    sq_2025.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2025)&\
        ((auth_df["quartile"]!="Q1")&(auth_df["quartile"]!="Q2")&(auth_df["quartile"]!="Q3")&(auth_df["quartile"]!="Q4"))]))
    q1_2024.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2024)&(auth_df["quartile"]=="Q1")]))
    q2_2024.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2024)&(auth_df["quartile"]=="Q2")]))
    q3_2024.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2024)&(auth_df["quartile"]=="Q3")]))
    q4_2024.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2024)&(auth_df["quartile"]=="Q4")]))
    sq_2024.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2024)&\
        ((auth_df["quartile"]!="Q1")&(auth_df["quartile"]!="Q2")&(auth_df["quartile"]!="Q3")&(auth_df["quartile"]!="Q4"))]))
    q1_2023.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2023)&(auth_df["quartile"]=="Q1")]))
    q2_2023.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2023)&(auth_df["quartile"]=="Q2")]))
    q3_2023.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2023)&(auth_df["quartile"]=="Q3")]))
    q4_2023.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2023)&(auth_df["quartile"]=="Q4")]))
    sq_2023.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2023)&\
        ((auth_df["quartile"]!="Q1")&(auth_df["quartile"]!="Q2")&(auth_df["quartile"]!="Q3")&(auth_df["quartile"]!="Q4"))]))
    q1_2022.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2022)&(auth_df["quartile"]=="Q1")]))
    q2_2022.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2022)&(auth_df["quartile"]=="Q2")]))
    q3_2022.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2022)&(auth_df["quartile"]=="Q3")]))
    q4_2022.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2022)&(auth_df["quartile"]=="Q4")]))
    sq_2022.append(len(auth_df[(auth_df["author_id"]==i)&(auth_df["year"]==2022)&\
        ((auth_df["quartile"]!="Q1")&(auth_df["quartile"]!="Q2")&(auth_df["quartile"]!="Q3")&(auth_df["quartile"]!="Q4"))]))

In [ ]:
import datetime as dt
year_now=pd.Timestamp.now().year
summary_final=pd.DataFrame({"Autor ID":autor_sc,"Autor Name":nameautor,
                            "H-index":h,"H5yr-index":h5,
                            "Q1_2025":q1_2025,"Q2_2025":q2_2025,"Q3_2025":q3_2025,"Q4_2025":q4_2025,"SQ_2025":sq_2025,
                            "Q1_2024":q1_2024,"Q2_2024":q2_2024,"Q3_2024":q3_2024,"Q4_2024":q4_2024,"SQ_2024":sq_2024,
                            "Q1_2023":q1_2023,"Q2_2023":q2_2023,"Q3_2023":q3_2023,"Q4_2023":q4_2023,"SQ_2023":sq_2023,
                            "Q1_2022":q1_2022,"Q2_2022":q2_2022,"Q3_2022":q3_2022,"Q4_2022":q4_2022,"SQ_2022":sq_2022})

In [ ]:
summary_final.sort_values(by="H-index",ascending=False).head(2)

In [ ]:
datautb.set_index("Autor ID",inplace=True)
summary_final.set_index("Autor ID",inplace=True)
summary_final["Total 2025"]=summary_final[["Q1_2025","Q2_2025","Q3_2025","Q4_2025"]].sum(axis=1)
summary_final["Total 2025 (include SQ)"]=summary_final[["Q1_2025","Q2_2025","Q3_2025","Q4_2025","SQ_2025"]].sum(axis=1)
summary_final["Total 2024"]=summary_final[["Q1_2024","Q2_2024","Q3_2024","Q4_2024"]].sum(axis=1)
summary_final["Total 2024 (include SQ)"]=summary_final[["Q1_2024","Q2_2024","Q3_2024","Q4_2024","SQ_2024"]].sum(axis=1)
summary_final["Total 2023"]=summary_final[["Q1_2023","Q2_2023","Q3_2023","Q4_2023"]].sum(axis=1)
summary_final["Total 2023 (include SQ)"]=summary_final[["Q1_2023","Q2_2023","Q3_2023","Q4_2023","SQ_2023"]].sum(axis=1)
summary_final["Total 2022"]=summary_final[["Q1_2022","Q2_2022","Q3_2022","Q4_2022"]].sum(axis=1)
summary_final["Total 2022 (include SQ)"]=summary_final[["Q1_2022","Q2_2022","Q3_2022","Q4_2022","SQ_2022"]].sum(axis=1)

In [ ]:
data1=datautb.merge(summary_final,left_index=True, right_index=True)\
    .sort_values(by=["H-index"],ascending=False)
data1.to_excel("MidataMiScript.xlsx")
data1

In [ ]:
auth_df=auth_df.rename(columns={"author_id":"Autor ID"})
auth_df.set_index("Autor ID",inplace=True)

In [ ]:
data2=datautb.merge(auth_df,left_index=True, right_index=True)\
    .sort_values(by=["year"],ascending=False)
data2.to_excel("MidataMiScript2.xlsx")
data2

In [ ]:
data1.sort_values(by="Total 2025", ascending=False).head(15)

In [ ]:
print("DOne...! Archivos generados...!")

Plots...

In [ ]:
dat_ETD=data1[(data1["ESCUELA"]=="ESCUELA DE TRANSFORMACIÓN DIGITAL")&(data1["Total 2025 (include SQ)"]>0)]

In [ ]:
cmap = plt.get_cmap('Blues_r')
colors = [cmap(i) for i in np.arange(0.2, 0.9, 0.15)]

In [ ]:
dat_ETD

In [ ]:
dat_ETD.set_index("DOCENTE")\
    .sort_values(by="Total 2025 (include SQ)",ascending=True)[["Q1_2025","Q2_2025","Q3_2025","Q4_2025","SQ_2025"]].tail(15)\
    .plot.barh(stacked=True, figsize=(12, 4), color=colors, edgecolor='k', lw=0.2)
plt.grid(alpha=0.1); plt.ylabel(None)
plt.title("2025 Production: Q1 = {}, Q2 = {}, Q3 = {}, Q4 = {}, SQ = {}, Total = {}".format(
    len(data2[(data2["ESCUELA"]=="ESCUELA DE TRANSFORMACIÓN DIGITAL")&(data2["quartile"]=="Q1")&(data2["year"]==2025)].drop_duplicates(subset="publication")),
          len(data2[(data2["ESCUELA"]=="ESCUELA DE TRANSFORMACIÓN DIGITAL")&(data2["quartile"]=="Q2")&(data2["year"]==2025)].drop_duplicates(subset="publication")),
len(data2[(data2["ESCUELA"]=="ESCUELA DE TRANSFORMACIÓN DIGITAL")&(data2["quartile"]=="Q3")&(data2["year"]==2025)].drop_duplicates(subset="publication")),
len(data2[(data2["ESCUELA"]=="ESCUELA DE TRANSFORMACIÓN DIGITAL")&(data2["quartile"]=="Q4")&(data2["year"]==2025)].drop_duplicates(subset="publication")),
len(data2[(data2["ESCUELA"]=="ESCUELA DE TRANSFORMACIÓN DIGITAL")&((data2["quartile"]=="-")|(data2["quartile"].isna()))&(data2["year"]==2025)].drop_duplicates(subset="publication")),
         len(data2[(data2["ESCUELA"]=="ESCUELA DE TRANSFORMACIÓN DIGITAL")&(data2["year"]==2025)].drop_duplicates(subset="publication"))))
plt.xticks(np.arange(0,dat_ETD["Total 2025 (include SQ)"].max()+1,1))
plt.tight_layout()
plt.savefig("ETD1.png",dpi=300,bbox_inches='tight')

In [ ]:
a=dat_ETD[["Q1_2025","Q2_2025","Q3_2025","Q4_2025","SQ_2025"]].\
    drop(columns=[c for c in ["Q1_2025","Q2_2025","Q3_2025","Q4_2025","SQ_2025"] if dat_ETD[c].sum()==0])
a.T.sum(axis=1).plot.pie(autopct='%1.1f%%',
                         figsize=(4,4),
                         explode=[0.1 for i in range(len(a.columns))],
                         pctdistance=0.8,
                         wedgeprops={'linewidth': 1},
                         cmap=cmap,
                         colors=colors,
                         textprops={'color': 'k', 'fontweight': None},
                         shadow=False)
plt.tight_layout()
plt.savefig("ETD2.png",dpi=150,bbox_inches='tight')
plt.show()

In [ ]:
summ2=pd.crosstab(data2[data2["year"]==2025].drop_duplicates(subset="publication")[["quartile","ESCUELA"]].reset_index()["ESCUELA"],
                       data2[data2["year"]==2025].drop_duplicates(subset="publication")[["quartile","ESCUELA"]].reset_index()["quartile"])

In [ ]:
summ2.index.name=""

In [ ]:
summ2["Total"]=summ2.sum(axis=1)
summ2

In [ ]:
import seaborn as sns
plt.figure(figsize=(12,4))
plt.title("2025 Production")
sns.heatmap(summ2,cmap="Blues",color=colors,annot=True)
plt.tight_layout()
plt.savefig("ETD3.png",dpi=300,bbox_inches='tight')
plt.show()

In [ ]:
data1.set_index("DOCENTE")\
    .sort_values(by="Total 2025 (include SQ)",ascending=True)[["Q1_2025","Q2_2025","Q3_2025","Q4_2025","SQ_2025"]].tail(15)\
    .plot.barh(stacked=True, figsize=(12, 4), color=colors, edgecolor='k', lw=0.2)
plt.xticks(np.arange(0,data1["Total 2025 (include SQ)"].max()+1,1))
plt.tight_layout()
plt.savefig("ALL.png",dpi=300,bbox_inches='tight')
plt.show()